# CMake generated Testfile for 
# Source directory: /mnt/d/Stuff/wxy/libsnark/libsnark
# Build directory: /mnt/d/Stuff/wxy/libsnark/build-debug/libsnark
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(common_routing_algorithms_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/common_routing_algorithms_test")
set_tests_properties(common_routing_algorithms_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;680;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib1_simple_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/gadgetlib1_simple_test")
set_tests_properties(gadgetlib1_simple_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;684;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib1_r1cs_ppzksnark_verifier_gadget_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/gadgetlib1_r1cs_ppzksnark_verifier_gadget_test")
set_tests_properties(gadgetlib1_r1cs_ppzksnark_verifier_gadget_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;688;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_adapters_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/gadgetlib2_adapters_test")
set_tests_properties(gadgetlib2_adapters_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;692;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_constraint_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/gadgetlib2_constraint_test")
set_tests_properties(gadgetlib2_constraint_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;696;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_gadget_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/gadgetlib2_gadget_test")
set_tests_properties(gadgetlib2_gadget_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;700;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_integration_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/gadgetlib2_integration_test")
set_tests_properties(gadgetlib2_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;704;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_protoboard_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/gadgetlib2_protoboard_test")
set_tests_properties(gadgetlib2_protoboard_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;708;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(gadgetlib2_variable_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/gadgetlib2_variable_test")
set_tests_properties(gadgetlib2_variable_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;712;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(relations_qap_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/relations_qap_test")
set_tests_properties(relations_qap_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;716;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(relations_sap_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/relations_sap_test")
set_tests_properties(relations_sap_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;720;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(relations_ssp_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/relations_ssp_test")
set_tests_properties(relations_ssp_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;724;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_bacs_ppzksnark_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/zk_proof_systems_bacs_ppzksnark_test")
set_tests_properties(zk_proof_systems_bacs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;728;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_r1cs_ppzksnark_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/zk_proof_systems_r1cs_ppzksnark_test")
set_tests_properties(zk_proof_systems_r1cs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;732;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_r1cs_se_ppzksnark_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/zk_proof_systems_r1cs_se_ppzksnark_test")
set_tests_properties(zk_proof_systems_r1cs_se_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;736;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_r1cs_gg_ppzksnark_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/zk_proof_systems_r1cs_gg_ppzksnark_test")
set_tests_properties(zk_proof_systems_r1cs_gg_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;740;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_ram_ppzksnark_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/zk_proof_systems_ram_ppzksnark_test")
set_tests_properties(zk_proof_systems_ram_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;744;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_tbcs_ppzksnark_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/zk_proof_systems_tbcs_ppzksnark_test")
set_tests_properties(zk_proof_systems_tbcs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;748;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(zk_proof_systems_uscs_ppzksnark_test "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/zk_proof_systems_uscs_ppzksnark_test")
set_tests_properties(zk_proof_systems_uscs_ppzksnark_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;752;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(test_knapsack_gadget "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/test_knapsack_gadget")
set_tests_properties(test_knapsack_gadget PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;756;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(test_merkle_tree_gadgets "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/test_merkle_tree_gadgets")
set_tests_properties(test_merkle_tree_gadgets PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;760;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(test_set_commitment_gadget "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/test_set_commitment_gadget")
set_tests_properties(test_set_commitment_gadget PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;764;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
add_test(test_sha256_gadget "/mnt/d/Stuff/wxy/libsnark/build-debug/libsnark/test_sha256_gadget")
set_tests_properties(test_sha256_gadget PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;768;add_test;/mnt/d/Stuff/wxy/libsnark/libsnark/CMakeLists.txt;0;")
